### ISSUE TITLE
Add screenshots to README?

### ISSUE THREAD

**Issue by ArniDagur** [IIIM-IS/AERA_Visualizer#1]
Hey @jefft0,

Since I run Linux as my daily driver, I can neither run this project nor AERA. However, I'm quite interested to see what `AERA_Visualizer` looks like. Do you mind posting a screenshot or two, and putting them in the README?

Thanks!

**Comment by jefft0** [comment]
![screenshot](https://user-images.githubusercontent.com/1999543/149375651-3f93f934-18c9-425b-b507-03646149239f.png)
